// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: ai_lab_runs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqCreateTrain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCreateTrain) Reset() {
	*x = ReqCreateTrain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCreateTrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateTrain) ProtoMessage() {}

func (x *ReqCreateTrain) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateTrain.ProtoReflect.Descriptor instead.
func (*ReqCreateTrain) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{0}
}

type ReqCreateTrainEval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCreateTrainEval) Reset() {
	*x = ReqCreateTrainEval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCreateTrainEval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateTrainEval) ProtoMessage() {}

func (x *ReqCreateTrainEval) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateTrainEval.ProtoReflect.Descriptor instead.
func (*ReqCreateTrainEval) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{1}
}

type ReqSaveTrain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqSaveTrain) Reset() {
	*x = ReqSaveTrain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSaveTrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSaveTrain) ProtoMessage() {}

func (x *ReqSaveTrain) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSaveTrain.ProtoReflect.Descriptor instead.
func (*ReqSaveTrain) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{2}
}

type ReqStartTrainVisual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStartTrainVisual) Reset() {
	*x = ReqStartTrainVisual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStartTrainVisual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStartTrainVisual) ProtoMessage() {}

func (x *ReqStartTrainVisual) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStartTrainVisual.ProtoReflect.Descriptor instead.
func (*ReqStartTrainVisual) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{3}
}

type ReqStopTrainVisual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStopTrainVisual) Reset() {
	*x = ReqStopTrainVisual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopTrainVisual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopTrainVisual) ProtoMessage() {}

func (x *ReqStopTrainVisual) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopTrainVisual.ProtoReflect.Descriptor instead.
func (*ReqStopTrainVisual) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{4}
}

type ReqListRuns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqListRuns) Reset() {
	*x = ReqListRuns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqListRuns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqListRuns) ProtoMessage() {}

func (x *ReqListRuns) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqListRuns.ProtoReflect.Descriptor instead.
func (*ReqListRuns) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{5}
}

type AILabRunList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AILabRunList) Reset() {
	*x = AILabRunList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AILabRunList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AILabRunList) ProtoMessage() {}

func (x *AILabRunList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AILabRunList.ProtoReflect.Descriptor instead.
func (*AILabRunList) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{6}
}

type ReqCtrlRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCtrlRun) Reset() {
	*x = ReqCtrlRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCtrlRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCtrlRun) ProtoMessage() {}

func (x *ReqCtrlRun) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCtrlRun.ProtoReflect.Descriptor instead.
func (*ReqCtrlRun) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{7}
}

type AILabRunDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AILabRunDetail) Reset() {
	*x = AILabRunDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AILabRunDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AILabRunDetail) ProtoMessage() {}

func (x *AILabRunDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AILabRunDetail.ProtoReflect.Descriptor instead.
func (*AILabRunDetail) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{8}
}

type ReqStatsRuns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqStatsRuns) Reset() {
	*x = ReqStatsRuns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStatsRuns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStatsRuns) ProtoMessage() {}

func (x *ReqStatsRuns) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStatsRuns.ProtoReflect.Descriptor instead.
func (*ReqStatsRuns) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{9}
}

type AILabRunStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AILabRunStats) Reset() {
	*x = AILabRunStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AILabRunStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AILabRunStats) ProtoMessage() {}

func (x *AILabRunStats) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AILabRunStats.ProtoReflect.Descriptor instead.
func (*AILabRunStats) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{10}
}

type ReqCleanStrategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqCleanStrategy) Reset() {
	*x = ReqCleanStrategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_lab_runs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCleanStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCleanStrategy) ProtoMessage() {}

func (x *ReqCleanStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ai_lab_runs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCleanStrategy.ProtoReflect.Descriptor instead.
func (*ReqCleanStrategy) Descriptor() ([]byte, []int) {
	return file_ai_lab_runs_proto_rawDescGZIP(), []int{11}
}

var File_ai_lab_runs_proto protoreflect.FileDescriptor

var file_ai_lab_runs_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x5f, 0x72, 0x75, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x45, 0x76, 0x61, 0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71,
	0x53, 0x61, 0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x71,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x56, 0x69, 0x73, 0x75, 0x61, 0x6c,
	0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x56, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x75, 0x6e, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x49, 0x4c, 0x61, 0x62, 0x52, 0x75,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x43, 0x74, 0x72, 0x6c,
	0x52, 0x75, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x49, 0x4c, 0x61, 0x62, 0x52, 0x75, 0x6e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x75, 0x6e, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x49, 0x4c, 0x61, 0x62, 0x52, 0x75,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x43, 0x6c, 0x65,
	0x61, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x32, 0xe0, 0x05, 0x0a, 0x08, 0x41,
	0x49, 0x4c, 0x61, 0x62, 0x52, 0x75, 0x6e, 0x12, 0x3a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x1a, 0x18, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61,
	0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x71,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x45, 0x76, 0x61, 0x6c, 0x1a,
	0x18, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x53,
	0x61, 0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x0d, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x61,
	0x76, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x1a, 0x18, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61,
	0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x56, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x12, 0x14, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x56, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x1a, 0x18, 0x2e,
	0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0f, 0x53, 0x74, 0x6f,
	0x70, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x56, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x12, 0x13, 0x2e, 0x52,
	0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x56, 0x69, 0x73, 0x75, 0x61,
	0x6c, 0x1a, 0x18, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x29, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x73, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x73, 0x1a, 0x0d, 0x2e, 0x41, 0x49, 0x4c, 0x61, 0x62, 0x52,
	0x75, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x74, 0x72, 0x6c,
	0x52, 0x75, 0x6e, 0x12, 0x0b, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x74, 0x72, 0x6c, 0x52, 0x75, 0x6e,
	0x1a, 0x18, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x08,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x75, 0x6e, 0x12, 0x16, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e,
	0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x1a, 0x0f, 0x2e, 0x41, 0x49, 0x4c, 0x61, 0x62, 0x52, 0x75, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x75, 0x6e, 0x73,
	0x12, 0x0d, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x75, 0x6e, 0x73, 0x1a,
	0x0e, 0x2e, 0x41, 0x49, 0x4c, 0x61, 0x62, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x52, 0x75,
	0x6e, 0x73, 0x12, 0x16, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62,
	0x2e, 0x52, 0x65, 0x71, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x6d, 0x6f,
	0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x4c,
	0x61, 0x62, 0x52, 0x75, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69,
	0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x18,
	0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x10, 0x53, 0x65,
	0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x11,
	0x2e, 0x52, 0x65, 0x71, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x1a, 0x18, 0x2e, 0x62, 0x6d, 0x6f, 0x64, 0x2e, 0x61, 0x69, 0x5f, 0x6c, 0x61, 0x62, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ai_lab_runs_proto_rawDescOnce sync.Once
	file_ai_lab_runs_proto_rawDescData = file_ai_lab_runs_proto_rawDesc
)

func file_ai_lab_runs_proto_rawDescGZIP() []byte {
	file_ai_lab_runs_proto_rawDescOnce.Do(func() {
		file_ai_lab_runs_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_lab_runs_proto_rawDescData)
	})
	return file_ai_lab_runs_proto_rawDescData
}

var file_ai_lab_runs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ai_lab_runs_proto_goTypes = []interface{}{
	(*ReqCreateTrain)(nil),      // 0: ReqCreateTrain
	(*ReqCreateTrainEval)(nil),  // 1: ReqCreateTrainEval
	(*ReqSaveTrain)(nil),        // 2: ReqSaveTrain
	(*ReqStartTrainVisual)(nil), // 3: ReqStartTrainVisual
	(*ReqStopTrainVisual)(nil),  // 4: ReqStopTrainVisual
	(*ReqListRuns)(nil),         // 5: ReqListRuns
	(*AILabRunList)(nil),        // 6: AILabRunList
	(*ReqCtrlRun)(nil),          // 7: ReqCtrlRun
	(*AILabRunDetail)(nil),      // 8: AILabRunDetail
	(*ReqStatsRuns)(nil),        // 9: ReqStatsRuns
	(*AILabRunStats)(nil),       // 10: AILabRunStats
	(*ReqCleanStrategy)(nil),    // 11: ReqCleanStrategy
	(*ReqTarget)(nil),           // 12: bmod.ai_lab.ReqTarget
	(*ReplyHeader)(nil),         // 13: bmod.ai_lab.ReplyHeader
}
var file_ai_lab_runs_proto_depIdxs = []int32{
	0,  // 0: AILabRun.CreateTrain:input_type -> ReqCreateTrain
	1,  // 1: AILabRun.CreateTrainEvaluate:input_type -> ReqCreateTrainEval
	2,  // 2: AILabRun.SaveTrain:input_type -> ReqSaveTrain
	3,  // 3: AILabRun.StartTrainVisual:input_type -> ReqStartTrainVisual
	4,  // 4: AILabRun.StopTrainVisual:input_type -> ReqStopTrainVisual
	5,  // 5: AILabRun.ListRuns:input_type -> ReqListRuns
	7,  // 6: AILabRun.CtrlRun:input_type -> ReqCtrlRun
	12, // 7: AILabRun.QueryRun:input_type -> bmod.ai_lab.ReqTarget
	9,  // 8: AILabRun.StatsRuns:input_type -> ReqStatsRuns
	12, // 9: AILabRun.DeleteLabRuns:input_type -> bmod.ai_lab.ReqTarget
	12, // 10: AILabRun.CleanLabRuns:input_type -> bmod.ai_lab.ReqTarget
	11, // 11: AILabRun.SetCleanStrategy:input_type -> ReqCleanStrategy
	13, // 12: AILabRun.CreateTrain:output_type -> bmod.ai_lab.ReplyHeader
	13, // 13: AILabRun.CreateTrainEvaluate:output_type -> bmod.ai_lab.ReplyHeader
	13, // 14: AILabRun.SaveTrain:output_type -> bmod.ai_lab.ReplyHeader
	13, // 15: AILabRun.StartTrainVisual:output_type -> bmod.ai_lab.ReplyHeader
	13, // 16: AILabRun.StopTrainVisual:output_type -> bmod.ai_lab.ReplyHeader
	6,  // 17: AILabRun.ListRuns:output_type -> AILabRunList
	13, // 18: AILabRun.CtrlRun:output_type -> bmod.ai_lab.ReplyHeader
	8,  // 19: AILabRun.QueryRun:output_type -> AILabRunDetail
	10, // 20: AILabRun.StatsRuns:output_type -> AILabRunStats
	13, // 21: AILabRun.DeleteLabRuns:output_type -> bmod.ai_lab.ReplyHeader
	13, // 22: AILabRun.CleanLabRuns:output_type -> bmod.ai_lab.ReplyHeader
	13, // 23: AILabRun.SetCleanStrategy:output_type -> bmod.ai_lab.ReplyHeader
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ai_lab_runs_proto_init() }
func file_ai_lab_runs_proto_init() {
	if File_ai_lab_runs_proto != nil {
		return
	}
	file_ai_lab_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ai_lab_runs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCreateTrain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCreateTrainEval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSaveTrain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStartTrainVisual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopTrainVisual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqListRuns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AILabRunList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCtrlRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AILabRunDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStatsRuns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AILabRunStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_lab_runs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCleanStrategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_lab_runs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_lab_runs_proto_goTypes,
		DependencyIndexes: file_ai_lab_runs_proto_depIdxs,
		MessageInfos:      file_ai_lab_runs_proto_msgTypes,
	}.Build()
	File_ai_lab_runs_proto = out.File
	file_ai_lab_runs_proto_rawDesc = nil
	file_ai_lab_runs_proto_goTypes = nil
	file_ai_lab_runs_proto_depIdxs = nil
}
