{{- $pvType := .Values.storage.persistentVolumeType  }}
{{- if or (eq $pvType "nfs") (eq $pvType "hostPath") }}
{{- range .Values.storage.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}-pv
spec:
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .name }}-sc
  persistentVolumeReclaimPolicy: Retain
{{- if eq $pvType "nfs"  }}
  mountOptions:
    - timeo=20
    - tcp
  nfs:
    {{- if not (empty $.Values.storage.nfsServer) }}
    server: {{ $.Values.storage.nfsServer }}
    {{- end }}
    {{- if not (empty .path) }}
    path: {{ .path }}
    {{- end }}
{{- else }}
  hostPath:
    path: {{ .path }}
{{- end  }}
{{- end  }}
{{- range .Values.storage.persistentVolumes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .name  }}
spec:
  storageClassName: {{ .name }}-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .claimCapacity }}

{{- end }}
{{- end }}
