apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-lab.fullname" . }}
  labels:
    {{- include "ai-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "ai-lab.selectorLabels" . | nindent 4 }}
